MAX_N_CLUSTERS = 10
N_KERNELS_SPAN = 3
N_GAUSSIAN_MIXTURE_INIT = 1
GMM_INIT_PARAMS = "k-means++"
DEFAULT_VARIANCE_RETAINED = 0.8
MAX_N_COMPONENTS = 100
DATAPOINTS_LIMIT = 2000
N_DISPLAYED_FEATURES = 3
MAX_DIMENSION_TSNE_INPUT = 50
TSNE_DIMENSION = 2
N_RANDOM_SAMPLE = 100
MAX_DATATABLE_NCOLUMNS = 50
DEFAULT_PERPLEXITY = 30
DEFAULT_N_COLOR_BINS = 100

LOG_PROBABILITY_CMAP = "viridis_r"
FEATURES_CMAP = "RdYlGn_r"
